Do not crash on an empty view
When someone creates a new view on the project board by clicking on
"+New View" and does not do anything more, an empty view will be
created and saved, which will make our bot to fail on the following
error when querying for the project's views:
```
  File ".../gitHub-automation/gh_project_automation.py", line 478, in run
    while m := filter_cats.search(f):
               ^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
```
We cannot pass `None` to the regexp search, hence I just added a check
to skip such views - they don't have any filters/labels either way.